services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dsa-ide-backend
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
